// src/shared/config/icons/global.icons.js
import {
  Building2Icon,
  ChevronDownIcon,
  FlagIcon,
  HandshakeIcon,
  HeartIcon,
  MailIcon,
  PhoneIcon,
  PinIcon,
  PlaneIcon,
  ShieldIcon,
  StarIcon,
  TourBusIcon,
  UsersIcon,
  FacebookIcon,
  InstagramIcon,
  GlobeIcon,
  BoltIcon,
  RecycleIcon,
} from "../../ui/icons/index.js";

export const GLOBAL_ICONS = Object.freeze({
  Building2Icon,
  ChevronDownIcon,
  FlagIcon,
  HandshakeIcon,
  HeartIcon,
  MailIcon,
  PhoneIcon,
  PinIcon,
  PlaneIcon,
  ShieldIcon,
  StarIcon,
  TourBusIcon,
  UsersIcon,
  FacebookIcon,
  InstagramIcon,
  GlobeIcon,
  BoltIcon,
  RecycleIcon,
});
