// src/shared/config/BrandIcons.jsx
import {
  FacebookIcon,
  InstagramIcon,
  MailIcon,
  PhoneIcon,
  GlobeIcon,
  PinIcon,
  CardIcon,
  ShieldIcon,
  MedalIcon,
  PlaneIcon,
  BusIcon,
  TourBusIcon,
  PackageIcon,
  HandshakeIcon,
  StarIcon,
  TravelVector,
  ChevronDownIcon,
  BrainIcon,
  UsersIcon,
  HeartIcon,
  SpeedIcon,
  SunIcon,
  DreamIcon,
  BoltIcon,
  FlagIcon,
  MonitorIcon,
  RecycleIcon,
  GraduationCapIcon,
  CompassIcon,
  BrushCleaningIcon,
  AthleteBarbellIcon,
  ClockIcon,
  ChartIcon,
  EyeIcon,
  ConsultingExperienceIcon,
  AppleIcon,
  VideoIcon,
  SearchIcon,
  BicepsFlexedIcon,
  PhysicalTherapyIcon,
  SmileIcon,
  SoupIcon,
  BedIcon,
  ShirtIcon,
  LuggageIcon,
  TrendUpIcon,
  CogIcon,
  CircusTentIcon,
  Building2Icon,
  GoalIcon,
  ChartFrameIcon,
  BikeIcon,
  WorkflowIcon,
  JudoIcon,
  FencingIcon,
  HandballIcon,
  VolleyballIcon,
  SurfIcon,
} from "../ui/icons/index.js";

/* ===== Flags (componentes) ===== */
import {
  MaltaFlag,
  QatarFlag,
  KuwaitFlag,
  LebanonFlag,
  IraqFlag,
  BrazilFlag,
  SaudiArabiaFlag,
  PortugalFlag,
} from "../ui/icons/flags/index.js";

/**
 * Apenas reexports de componentes/ícones.
 * Não meter helpers aqui.
 */
export const ICONS = Object.freeze({
  FacebookIcon,
  InstagramIcon,
  MailIcon,
  PhoneIcon,
  GlobeIcon,
  PinIcon,
  CardIcon,
  ShieldIcon,
  MedalIcon,
  PlaneIcon,
  BusIcon,
  TourBusIcon,
  PackageIcon,
  HandshakeIcon,
  StarIcon,
  TravelVector,
  ChevronDownIcon,
  BrainIcon,
  UsersIcon,
  HeartIcon,
  SpeedIcon,
  SunIcon,
  DreamIcon,
  BoltIcon,
  FlagIcon,
  MonitorIcon,
  RecycleIcon,
  GraduationCapIcon,
  CompassIcon,
  BrushCleaningIcon,
  AthleteBarbellIcon,
  ClockIcon,
  ChartIcon,
  EyeIcon,
  ConsultingExperienceIcon,
  AppleIcon,
  VideoIcon,
  SearchIcon,
  BicepsFlexedIcon,
  PhysicalTherapyIcon,
  SmileIcon,
  SoupIcon,
  BedIcon,
  ShirtIcon,
  LuggageIcon,
  TrendUpIcon,
  CogIcon,
  CircusTentIcon,
  Building2Icon,
  GoalIcon,
  ChartFrameIcon,
  BikeIcon,
  WorkflowIcon,
  JudoIcon,
  FencingIcon,
  HandballIcon,
  VolleyballIcon,
  SurfIcon,
});

export const FLAGS = Object.freeze({
  malta: MaltaFlag,
  qatar: QatarFlag,
  kuwait: KuwaitFlag,
  lebanon: LebanonFlag,
  iraq: IraqFlag,
  saudiArabia: SaudiArabiaFlag,
  brazil: BrazilFlag,
  portugal: PortugalFlag,
});
