import {
  AppleIcon,
  AthleteBarbellIcon,
  BrainIcon,
  BrushCleaningIcon,
  ChartFrameIcon,
  ChartIcon,
  CircusTentIcon,
  ClockIcon,
  CogIcon,
  CompassIcon,
  ConsultingExperienceIcon,
  DreamIcon,
  EyeIcon,
  GoalIcon,
  GraduationCapIcon,
  LuggageIcon,
  MedalIcon,
  MonitorIcon,
  PhysicalTherapyIcon,
  SearchIcon,
  ShirtIcon,
  SmileIcon,
  SoupIcon,
  SpeedIcon,
  SunIcon,
  TrendUpIcon,
  VideoIcon,
  WorkflowIcon,
} from "../../shared/ui/icons/index.js";

export const BRAND_ICONS = Object.freeze({
  AppleIcon,
  AthleteBarbellIcon,
  BrainIcon,
  BrushCleaningIcon,
  ChartFrameIcon,
  ChartIcon,
  CircusTentIcon,
  ClockIcon,
  CogIcon,
  CompassIcon,
  ConsultingExperienceIcon,
  DreamIcon,
  EyeIcon,
  GoalIcon,
  GraduationCapIcon,
  LuggageIcon,
  MedalIcon,
  MonitorIcon,
  PhysicalTherapyIcon,
  SearchIcon,
  ShirtIcon,
  SmileIcon,
  SoupIcon,
  SpeedIcon,
  SunIcon,
  TrendUpIcon,
  VideoIcon,
  WorkflowIcon,
});

export default BRAND_ICONS;
