import {
  AppleIcon,
  AthleteBarbellIcon,
  BrainIcon,
  BrushCleaningIcon,
  ChartFrameIcon,
  ChartIcon,
  CircusTentIcon,
  ClockIcon,
  CogIcon,
  CompassIcon,
  ConsultingExperienceIcon,
  DreamIcon,
  EyeIcon,
  GoalIcon,
  GraduationCapIcon,
  BasketIcon,
  GymnasticsIcon,

  
 
  MonitorIcon,
  PhysicalTherapyIcon,
  SearchIcon,
  ShirtIcon,
  SmileIcon,
  SoupIcon,
  SpeedIcon,
  SunIcon,
  TrendUpIcon,
  VideoIcon,
  WorkflowIcon,
} from "../../shared/ui/icons/index.js";

export const BRAND_ICONS = Object.freeze({
  AppleIcon,
  AthleteBarbellIcon,
  BrainIcon,
  BrushCleaningIcon,
  ChartFrameIcon,
  ChartIcon,
  CircusTentIcon,
  ClockIcon,
  CogIcon,
  CompassIcon,
  ConsultingExperienceIcon,
  DreamIcon,
  EyeIcon,
  GoalIcon,
  GraduationCapIcon,
  BasketIcon,
  GymnasticsIcon,


  MonitorIcon,
  PhysicalTherapyIcon,
  SearchIcon,
  ShirtIcon,
  SmileIcon,
  SoupIcon,
  SpeedIcon,
  SunIcon,
  TrendUpIcon,
  VideoIcon,
  WorkflowIcon,
});
