import {
  AirVentIcon,
  BathIcon,
  BrushCleaningIcon,
  BusinessPersonIcon,
  CardIcon,
  CelebrationIcon,
  CigaretteOffIcon,
  CircleOffIcon,
  ClockIcon,
  DeskIcon,
  FruitBasketIcon,
  MountainIcon,
  ThermalIcon,
  TowelRackIcon,
  TrophyIcon,
  TvIcon,
  UtensilsIcon,
  WardrobeIcon,
  WaterIcon,
  WifiIcon,
  WineIcon,
} from "../../shared/ui/icons/index.js";

export const BRAND_ICONS = Object.freeze({
  AirVentIcon,
  BathIcon,
  BrushCleaningIcon,
  BusinessPersonIcon,
  CardIcon,
  CelebrationIcon,
  CigaretteOffIcon,
  CircleOffIcon,
  ClockIcon,
  DeskIcon,
  FruitBasketIcon,
  MountainIcon,
  ThermalIcon,
  TowelRackIcon,
  TrophyIcon,
  TvIcon,
  UtensilsIcon,
  WardrobeIcon,
  WaterIcon,
  WifiIcon,
  WineIcon,
});

export default BRAND_ICONS;
